name: Duling Creative
favicon: null
layout_spectrum: 0.25435
typography_spectrum: 0.35289
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#353334'
    - '#f0f0f0'
    - '#9f9f9f'
    - '#636363'
    - '#cba043'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
