name: Duling Creative
favicon: null
layout_spectrum: 0.50877
typography_spectrum: 0.25297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#163146'
    - '#5f7d99'
    - '#050505'
    - '#3e586f'
    - '#aea7a1'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
