name: Duling Creative
favicon: null
layout_spectrum: 0.50877
typography_spectrum: 0.25297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#343434'
    - '#6d6d6d'
    - '#909090'
    - '#d7d7d7'
  brandStrength: 0.375
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
